"""empty message

Revision ID: 6265d78a9d36
Revises: 
Create Date: 2023-12-24 17:22:18.653408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6265d78a9d36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('url_img', sa.String(length=320), nullable=False),
    sa.Column('idu_img', sa.String(length=320), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('day_Date', sa.String(length=20), nullable=False),
    sa.Column('month_Date', sa.String(length=20), nullable=False),
    sa.Column('year_Date', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('name_contact', sa.String(length=80), nullable=False),
    sa.Column('num_contact', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name_contact'),
    sa.UniqueConstraint('username')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('url_img', sa.String(length=250), nullable=True),
    sa.Column('idu_img', sa.String(length=250), nullable=True),
    sa.Column('id_category', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_category'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('id_Product', sa.Integer(), nullable=False),
    sa.Column('id_Order', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_Order'], ['order.id'], ),
    sa.ForeignKeyConstraint(['id_Product'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    op.drop_table('product')
    op.drop_table('user')
    op.drop_table('order')
    op.drop_table('category')
    # ### end Alembic commands ###
